### ISSUE TITLE
Fix IE9 legend text wrapping

### ISSUE THREAD

**Issue by necolas** [necolas/normalize.css#100]
IE9 doesn't wrap `legend` text.

A quick look for a solution shows that adding `max-width: 100%` will cause IE9 to wrap text.

Need to do some tests to understand the impact of adding that declaration, e.g., people being caught out if they try to style the legend element and modify other box-model properties. Also check to see if there is an alternative fix that is cleaner.

**Comment by jonathantneal** [comment]
**Bad news**: This bug persists in Edge. **Good News**: It can be fixed! Also, few people report it.

**IE9-11** and **Edge 12-13** can be completely fixed using `box-sizing: border-box; max-width: 100%`, but IE8 will still experience some issues as “*the min-width property applies to content-box even if box-sizing is set to border-box*” [cite](http://caniuse.com/#search=content-box).

**IE8-11** can be fixed using the [456 Berea St fix](http://www.456bereastreet.com/archive/201210/how_to_line_wrap_text_in_legend_elements_even_in_ie/) `display: table; white-space: normal`, but this fix will not work at all for **Edge 12-13**.

Both can be combined for complete coverage:

```css
legend {
  box-sizing: border-box; /* IE9-11 & Edge 12-13 */
  display: table; /* IE8-11 */
  max-width: 100%; /* Patch for IE9-11 & Edge 12-13 */
  white-space: normal; /* IE8-11 */
}
```

That’s pretty horrid CSS. Moving forward for Normalize.css v4, I believe either IE8 support should be dropped or the Berea fix should be omitted (and then mentioned in extended detail notes). Many websites override `box-sizing` to be `border-box` these days, so the IE/Edge fix seems most reasonable.
