### ISSUE TITLE
Normalize default color scheme

### ISSUE THREAD

**Issue by ssokolow** [necolas/normalize.css#113]
One of the more subtle things that vary between browsers is default color scheme. Internet Explorer uses default link colors that are noticeably darker than all other browsers I test my sites on. (Firefox, Chrome, Opera, Midori for GTKWebKit, Arora for QtWebKit, and sometimes Konqueror)

I'd like to propose the addition of these lines to resolve that variance in favor of the default color scheme all other browsers seem to have agreed on:

``` css
body {
    color: #000;
    background-color: #fff;
}

a:link { color: #00e; }
a:visited { color: #800080; }
a:active { color: #e00; }
```

(I explicitly set the default background and foreground colors just in case a default (eg. user-customized, but not overriding) stylesheet may vary in a way incompatible with the link colors I set, as recommended by the W3C CSS validator.)
