### ISSUE TITLE
Chrome adds top and bottom spacing for controls on <input type="time"> 

### ISSUE THREAD

**Issue by Inkdpixels** [necolas/normalize.css#144]
As I worked on a recent project I discovered that Chrome adds some spacing on the controls for input type="time" as seen on this fiddle http://jsfiddle.net/ZdhEA/4/
A possible workaround would be to style the shadow dom, like this:

``` css
input::-webkit-datetime-edit {
    margin-top: -.17em;
    margin-bottom: -.17em;
}​
```

But the problem I see with this workaround is that the margin values needs to be changed as the font-size changes (I found no value wich suits all font-sizes). Is there any chance to get this fixed in a better way?
