### ISSUE TITLE
FileUpload fields

### ISSUE THREAD

**Issue by axgmc** [necolas/normalize.css#148]
The rule at line 298 should include the FileUpload fields:

``` css
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"],
input[type='file']::-webkit-file-upload-button {
    -webkit-appearance: button; /* 2 */
    cursor: pointer; /* 3 */
}
input[type='file'] {
    cursor: pointer;
}
```

Thanks for your excellent work!!
