### ISSUE TITLE
Textarea on Safari Mac

### ISSUE THREAD

**Issue by axgmc** [necolas/normalize.css#149]
Textarea on Safari Mac are not consistent with other input fields.
To resolve it, please add:

``` css
textarea {
    -webkit-appearance: textfield;
}
```
