### ISSUE TITLE
Placeholder bug in Firefox

### ISSUE THREAD

**Issue by axgmc** [necolas/normalize.css#150]
If one change the text color of input fields, Firefox will change the default color of placeholders too!
To fix this bug, please add:

``` css
input:-moz-placeholder,
textarea:-moz-placeholder {
    color: darkgray;
}
```
