### ISSUE TITLE
Normalize `select` element styling

### ISSUE THREAD

**Issue by axgmc** [necolas/normalize.css#151]
To allow `select` to have a height on Safari for Mac, and add some consistency between browsers, just add:

``` css
@media screen and (-webkit-min-device-pixel-ratio:0) { /* For Safari and Chrome */
    select {
        border-color: #adadb4; /* Turns off Aqua */ 
    }
}
```
