### ISSUE TITLE
Forms consistency

### ISSUE THREAD

**Issue by axgmc** [necolas/normalize.css#152]
Here is the CSS i use to make forms identical between latest versions of Safari, Firefox, Chrome and IE (if it can be useful):

``` css
input, select, button, textarea {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

input, select, button {
    vertical-align: middle;
}

input:not([type='image']) {
    min-height: 25px;   /* Avoid reducing 'file', 'color' and 'range' types */
}

input[type='checkbox'],
input[type='radio'] {
    min-height: 0;  /* Back to default */
    vertical-align: baseline;
}

input[type='button'],
input[type='reset'],
input[type='submit'],
select,
button {
    height: 25px;
}

@media screen and (-webkit-min-device-pixel-ratio:0) {  /* For Safari and Chrome */
input[type='range'] {
    min-height: 0;  /* Slider */
}
select {
    border-color: #adadb4;  /* Turns off Aqua to unlock height of drop-down lists in Safari */
}
}

textarea {
    height: 63px;   /* 3 lines */
}
```
