### ISSUE TITLE
Remove border-spacing: 0 in table element

### ISSUE THREAD

**Issue by huachend** [necolas/normalize.css#165]
I have tested removing `border-spacing: 0;` in IE6-10 / Chrome / Firefox / Safari / Opera, and found no difference between adding and removing it.

So, I think there is no use adding `border-spacing: 0` when `border-collapse: collapse` already exists.

That is, change from

``` css
table {
    border-collapse: collapse;
    border-spacing: 0;
}
```

to

``` css
table {
    border-collapse: collapse;
}
```

What do you think?
