### ISSUE TITLE
IE 10: Remove grey background on active links

### ISSUE THREAD

**Issue by sabl0r** [necolas/normalize.css#172]
IE 10 adds a background color to the active state of links.
Fix:

``` css
a:active {
    background-color: transparent;
}
```

Maybe you want to add this :)

**Comment by jonathantneal** [comment]
@tedw, just stumbled on this old issue and wanted to mention that it was changed to `background-color` in normalize v4.

**Comment by yisibl** [comment]
So this is better

```css
a {
  background-color: transparent;
}
```
