### ISSUE TITLE
IE10: remove clear icon on input elements

### ISSUE THREAD

**Issue by sabl0r** [necolas/normalize.css#195]
IE10 adds a clear icon to the right side of an input element.

![ie10](https://f.cloud.github.com/assets/1169879/498124/3167a658-bc0e-11e2-8fb0-9debcf6a53be.png)

This can be used to remove it:

``` css
input::-ms-clear {
    width: 0;
    height: 0;
}
```

`display: none;` can't be used because it interferes with a custom `padding-right`, see: http://stackoverflow.com/a/14739092/1171368
I tested the padding issue and can confirm it.
