### ISSUE TITLE
Support for Web Components

### ISSUE THREAD

**Issue by booch** [necolas/normalize.css#197]
The [Web Components spec](https://dvcs.w3.org/hg/webcomponents/raw-file/tip/explainer/index.html) adds some new elements. For older browsers that don't support Web Components, we should add some sane defaults. I'd recommend the following:

``` css
template, element, decorator, content, shadow { display: none; }
```

Although I'm not sure it's strictly necessary to include the content and shadow elements, as they are likely always contained within one of the other elements.
