### ISSUE TITLE
Do you really need `:not(:root)`?

### ISSUE THREAD

**Issue by zlatanvasovic** [necolas/normalize.css#237]
**From source:**

``` css
svg:not(:root) {
    overflow: hidden;
}
```

Do you need `:not(:root)`? `<svg>` isn't used as root element in HTML5.

**It's better to use:**

``` css
svg {
    overflow: hidden;
}
```
