### ISSUE TITLE
Missing resets for Safari? 

### ISSUE THREAD

**Issue by Orion98MC** [necolas/normalize.css#259]
Hey necolas,

I've run into an issue while using the normalize.css with bxslider (a jquery slider plugin).
There are browser specific default styles (in safari for instance) which add padding and margin to ul elements. Strangely I noticed it is not reset in normalize.css, although some other reset css do it. So I was wondering why is it not the case in normalize.css ?

These are the culprits:

``` css

-webkit-margin-before: 1em;
-webkit-margin-after: 1em;
-webkit-margin-start: 0px;
-webkit-margin-end: 0px;
-webkit-padding-start: 40px;

```

I had to add these to solve the issue:

``` css

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}

```

Regards,
Thierry
