### ISSUE TITLE
List style position

### ISSUE THREAD

**Issue by NKjoep** [necolas/normalize.css#281]
``` css
ol, ul {
    list-style-position: inside;
}
```

Do you think this could be useful?
I find sometimes ul/ol invading space with their symbols (list-style-type).
