### ISSUE TITLE
*:-moz-any(article, aside, nav, section) h1 formatting nested headings

### ISSUE THREAD

**Issue by beingzoe** [necolas/normalize.css#29]
While working on implementing a new HTML5 default markup scheme I discovered the Firefox UA stylesheet is already/actually using the proposed any() selector to adjust the size of h1 tags nested in html5 sectioning containers (from html.css in FF 6):

``` css
h3, *:-moz-any(article, aside, nav, section) *:-moz-any(article, aside, nav, section) h1 {
    display: block;
    font-size: 1.17em;
    font-weight: bold;
    margin: 1em 0;
}
```

Unfortunately only Firefox is doing this. The result for richly semantic html5 markup is FF 6 h1 tags sized dramatically smaller from all other browsers (only tested Chrome and IE). I discovered it while working on an improved default markup structure for projects, especially WordPress projects. Specifically when creating a section for the main content of a page with it's own h1 and then displaying many articles within it and their own h1 (i.e. a blog index) in order to achieve a semantically appropriate html5 outline. At that level there are now 3 nested h1 section headings.

I am working around it in my tests with:

``` css
*:-moz-any(article, aside, nav, section) h1 { font-size: 2em; font-weight: bold; margin: 0.67em 0; }
*:-webkit-any(article, aside, nav, section) h1 { font-size: 2em; font-weight: bold; margin: 0.67em 0; }
```

I included webkit because I read somewhere they had implemented the any() selector, though at this time they aren't actually imposing styling on. But I thought I would just play on the safe side in case any() is accepted in the specs. I guess I should add -o and -ms if I'm going that far?

While I can get behind the any() selector (and would indeed like to use it for similar cases) the result of Mozilla implementing this at this juncture within the UA stylesheet seems like something your project would be interesting in knowing about.

I would send a pull request but I haven't done enough testing on my "normalization" for this. But I wanted to bring it your attention because surely I am not the only one starting to implement more semantic rich html5 pages that might be affected by the inconsistency.
