### ISSUE TITLE
Duplicate font in code font-family declaration

### ISSUE THREAD

**Issue by JimBobSquarePants** [necolas/normalize.css#293]
https://github.com/necolas/normalize.css/blob/master/normalize.css#L229

``` css
code,
kbd,
pre,
samp {
  font-family: monospace, monospace;
  font-size: 1em;
}
```
