### ISSUE TITLE
Hide clear-button in IE10

### ISSUE THREAD

**Issue by thomas-rager** [necolas/normalize.css#307]
Microsoft Internet Explorer 10 shows a clear-button if an input-field has focus and is not empty. I think it would be nice to hide these clear-button by default.

``` css
::-ms-clear { display: none; }
```

![Clear-Button](http://i.msdn.microsoft.com/dynimg/IC559685.png)
