### ISSUE TITLE
Remove input & textarea background on firefox mobile

### ISSUE THREAD

**Issue by laino** [necolas/normalize.css#314]
All textareas/texfields (input) on firefox mobile (Android) have a weird looking gradient by default.

``` css
input, textarea {
    background-image: none;
}
```

would fix it.
