### ISSUE TITLE
Phrasing content increasing parent's line-height.

### ISSUE THREAD

**Issue by Paul-Browne** [necolas/normalize.css#329]
I've found that the line-height of a paragraph can grow if there is some phrasing content inside it, like so...

`<p>The <b>line-height</b> can sometimes change</p>`

It's easier to see what I mean from this pen

http://cdpn.io/uCyfp

The 'bug' effects different elements on a browser-to-browser basis, bold and strong are quite susceptible to 'growing' on chrome, also the font can affect weather or not the containing paragraph increases in line-height.

I've always found the best way to deal with this variable line-height is to add a reset to the css

``` css
a,small,s,q,u,i,b,strike,strong,mark,abbr,def,cite,var,kbd,span,em,ins,del,code,samp,sub,sup{line-height:1em}
```
