### ISSUE TITLE
Consider `box-sizing: inherit` instead of `box-sizing: content-box`

### ISSUE THREAD

**Issue by battaglr** [necolas/normalize.css#435]
**Current situation**

Among other styles, in the code-base we can find:

```css
hr {
  box-sizing: content-box;
}

input[type="search"] {
  box-sizing: content-box;
}
```

The use of `border-box` as "default" `box-sizing` in a lot of projects is rather common, usually using some variation of the code popularised by @paulirish:

```css
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

The problem with this, is that since the specificity of `*` is `[0,0,0,0]`, it will not override the `box-sizing` value of the `hr` –`[0,0,0,1]`– or the `input[type="search"]` –`[0,0,1,1]`–, and to accomplish consistency you must add these selectors to the code shown above, or something more specific like:

```css
input[type="search"] {
  box-sizing: border-box;
}
```

**Suggestion**

By replacing `box-sizing: content-box` with `box-sizing: inherit` we'll:

- Inherit the default `box-sizing` that is `content-box` in almost every browser, and accomplish the same results that we get using `content-box`.
- Allow an easy way to modify the `box-sizing` using current common techniques, without having to consider these specific cases.

The code will look something like:

```css
hr {
  box-sizing: inherit;
}

input[type="search"] {
  box-sizing: inherit;
}
```

What do you think, @necolas? [I'll be glad to do a PR](https://github.com/battaglr/normalize.css/commit/06097e88dc75c6c1da7672bfc090adeaf644cedc) if you want to add this.

**Test**

You can test this on different browsers using this [fiddle](http://goo.gl/RgXKlg).

---

I can't help thinking that I must be missing something, since this seems like something nobody had suggested here before, and the `box-sizing` value has been the topic of many opened issues.

**Comment by xPaw** [comment]
:+1: I had to remove box-sizing resets in normalize.css in one of my projects due to this exact reason.

**Comment by Mottie** [comment]
@battaglr There is an [updated recommendation](http://www.paulirish.com/2012/box-sizing-border-box-ftw/) in Paul Irish's blog:

```css
/* apply a natural box layout model to all elements, but allowing components to change */
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
