### ISSUE TITLE
Why the extra specific selector `html input[disabled]`?

### ISSUE THREAD

**Issue by henrik** [necolas/normalize.css#438]
This:

``` css
html input[disabled] {
  cursor: default;
}
```

means I have to get more specific to override it.

I'm sure there's good reason to have the `html` in there, but I'd love to understand why – and maybe a comment could be added to explain it? Happy to contribute that comment once I understand the reason.

**Comment by henrik** [comment]
Ah… I guess it is to win over `html input[type="button"]` in

``` css
/**
 * 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`
 *    and `video` controls.
 * 2. Correct inability to style clickable `input` types in iOS.
 * 3. Improve usability and consistency of cursor style between image-type
 *    `input` and others.
 */

button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button; /* 2 */
  cursor: pointer; /* 3 */
}
```

If so, how about splitting out `cursor: pointer; /* 3 */` into a separate selector group, so there's less unnecessary escalation of specificity? Specifically, wouldn't this work:

``` css
/**
 * 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`
 *    and `video` controls.
 * 2. Correct inability to style clickable `input` types in iOS.
 */

button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button; /* 2 */
}

/**
* Improve usability and consistency of cursor style between image-type `input` and others.
 */

button,
input[type="button"],
input[type="reset"],
input[type="submit"] {
  cursor: pointer; /* 3 */
}

/**
 * Re-set default cursor for disabled elements.
 */

button[disabled],
input[disabled] {
  cursor: default;
}
```
