### ISSUE TITLE
Set default tab-size to 4

### ISSUE THREAD

**Issue by Alhadis** [necolas/normalize.css#461]
Right, let's face it: the default tab-width of 8 characters used by systems and terminals really doesn't cut it for the web.

When code's indented with hard tabs, they're almost always 4-characters wide, not 8. Maybe have a global stylesheet rule to set the tab-size to a sensible value?

```css
*{
	tab-size: 4;
}
```

**Comment by toothbrush7777777** [comment]
Yes, that would be really useful. However, you also need to include `-moz-tab-size` and `-o-tab-size`.

**Comment by Alhadis** [comment]
Ah yeah, targeting `:root` would probably be preferable to making it universal (however universal I'd love to see 4-character-wide tabs being enforced...).

**Comment by toothbrush7777777** [comment]
@Alhadis That **would** make tabs 4 spaces wide across the whole document. The only advantage is that it allows overriding on a node and its descendants, like this:

```css
#some-plugin-which-relies-on-8-space-tabs {
    -moz-tab-size: 8;
      -o-tab-size: 8;
         tab-size: 8;
}
```

That way, we can override it for any element tree really easily.
