### ISSUE TITLE
Background reset only for active links

### ISSUE THREAD

**Issue by nazar-pc** [necolas/normalize.css#473]
This block is meant to affect only active links, but instead it affects all links, which was not intended and in my quite complex case caused problems.
[This line](https://github.com/necolas/normalize.css/blob/master/normalize.css#L90)

**Comment by battaglr** [comment]
Hi @nazar-pc, can you share that use-case? It may help to make an informed decision on closing or addressing this issue.

**Comment by nazar-pc** [comment]
No, I can't. It was connected with complex overriding of various properties under Shadow DOM (eventually I've removed this rule from my CSS).
Well, basically current selector have wider effect than it should according to comment near it.

**Comment by fvsch** [comment]
Changing the current code:
```css
a {
  background-color: transparent;
}
```
to:
```css
a:active {
  background-color: transparent;
}
```
would increase the style's specificity to `0.0.1.1`.

Users of normalize.css will get confused when their style for `.mybutton { background-color: skyblue; }` (specificy: `0.0.1.0`) is overriden by normalize.

**Comment by nazar-pc** [comment]
But it will override only `.mybutton:active`, it will not affect regular `.mybutton`

**Comment by fvsch** [comment]
It will override the styles for `.mybutton` when the user activates the link.
For instance if you have these styles:

```css
/* normalize */
a:active {
  background-color: transparent;
}

/* your styles */
.mybutton {
  color: white;
  background-color: #a00;
}
```
and the `.mybutton` link is on a white background, then when the user clicks the link it will disappear (white text with transparent background on white background).
