### ISSUE TITLE
Removing button border removes focus outline in FF

### ISSUE THREAD

**Issue by tdhooper** [necolas/normalize.css#481]
It's fairly common to want to remove button borders. If you do this while using normalize, the :focus style that keyboard users depend on will disappear in Firefox.

Tab through the links and buttons in the following examples for a demonstration:
* With normalize http://codepen.io/anon/pen/Gpmmqw/
* Without normalize http://codepen.io/anon/pen/rOmmKz

This is due to https://github.com/necolas/normalize.css/blob/master/normalize.css#L313

I'm using Firefox 40.0.3 on OS X

**Comment by robsonsobral** [comment]
I confirmed the issue on Firefox 43 on Windows.

Which is the result using only?

```css
button::-moz-focus-inner,
input::-moz-focus-inner {
  padding: 0;
}
```

**Comment by mobyou** [comment]
I confirm the focus outline issue also on the older Firefox (v41.0.1 on Windows).
The `border: 0` on this selector is a big accessibility issue.

@robsonsobral 
This CSS works :
```css
button::-moz-focus-inner,
input::-moz-focus-inner {
    padding: 0;
}
```

**Comment by akhyarrh** [comment]
Confirmed FF 43.0a2 (2015-10-13) Mint Rafaela

**Comment by tdhooper** [comment]
I've found that if we remove the border reset, #393 will return.

So instead of doing this, we can add the following to bring back the focus styling

````css
button:-moz-focusring,
input:-moz-focusring {
  outline: 1px dotted ButtonText;
}
````

I've taken this from the default Firefox styles http://mxr.mozilla.org/mozilla-release/source/layout/style/forms.css
