### ISSUE TITLE
Chrome added quote's to q element

### ISSUE THREAD

**Issue by gautamz07** [necolas/normalize.css#493]
I just used the following html:

```
<p>
	<q>Tried to hang a TV on my own. What a mistake! Khalaas handymen
mounted it properly in just a few minutes.</q>
	<cite>-JEANINE Chicago</cite>
</p>
```

And i saw the following being added in chrome. (the close and open quotes in chrome user agent).
can this behavior be normalized ? see screenshot below. 

http://i.imgur.com/z3yWu8O.jpg

**Comment by FagnerMartinsBrack** [comment]
That seems to be the intended behavior, see http://www.w3.org/TR/html-markup/q.html.

Is there any browser that **does not** use the following styles and need to be normalized?

```css
q {
  display: inline;
}
q:before {
  content: open-quote;
}
q:after {
  content: close-quote;
}
```
