### ISSUE TITLE
input[disabled] default color overwritten

### ISSUE THREAD

**Issue by remillc** [necolas/normalize.css#498]
**The problem**

We're used to see disabled buttons, select, inputs and textarea "grayed" at some point. But the following rule has the side effet of overwritting the browser's default stylesheets grayed color of disabled form control:

```css
button,
input,
optgroup,
select,
textarea {
  color: inherit; /* 1 */
  font: inherit; /* 2 */
  margin: 0; /* 3 */
}
```

Example default rule in Chrome:
```css
input[type="button" i]:disabled, 
input[type="submit" i]:disabled, 
input[type="reset" i]:disabled, 
input[type="file" i]:disabled::-webkit-file-upload-button, 
button:disabled, 
select:disabled, 
keygen:disabled, 
optgroup:disabled, 
option:disabled, 
select[disabled] > option {
	color: graytext;
}
```

As a result, an element `<input disabled="disabled>` will have the same color as an element `<input />`.

**The solution**

Using the negation pseudo-class `input:not([disabled])` will increase the specifity of the rule (1,1 > 1), so it can hurt developers' styles.

Setting back the default UA stylesheet color rule for `input[disabled]` won't change the specifity rule. Browsers however don't have the same default value:

Chrome v47 uses `graytext` (which is `#808080`, system color values are also [deprecated](https://drafts.csswg.org/css-color/#typedef-deprecated-system-color))

Firefox v42 uses value `#6d6d6d`
```css
button:disabled:active, 
button:disabled, 
input[type="reset"]:disabled:active, 
input[type="reset"]:disabled, 
input[type="button"]:disabled:active, 
input[type="button"]:disabled, 
select:disabled > button, 
select:disabled > button, 
input[type="submit"]:disabled:active, 
input[type="submit"]:disabled {
    color: #6D6D6D;
}
```
IE 11 (standard compliance mode): `#6d6d6d`

One solution could be to add back the browsers' default rules like so:

```css
button,
input,
optgroup,
select,
textarea {
  color: inherit; /* 1 */
  font: inherit; /* 2 */
  margin: 0; /* 3 */
}

/* add here */

input[type="button" i]:disabled, 
input[type="submit" i]:disabled, 
input[type="reset" i]:disabled, 
input[type="file" i]:disabled::-webkit-file-upload-button, 
button:disabled, 
select:disabled, 
keygen:disabled, 
optgroup:disabled, 
option:disabled, 
select[disabled] > option,
button:disabled:active, 
button:disabled, 

select:disabled > button {
    color: #6D6D6D;
}
```

It looks to my quit intrusive, so I suggest just dropping the `color` property:

```css
button,
input,
optgroup,
select,
textarea {
  font: inherit; /* 2 */
  margin: 0; /* 3 */
}
```
