### ISSUE TITLE
Wrong box-sizing in input[type="search"]

### ISSUE THREAD

**Issue by fmdalpiaz** [necolas/normalize.css#534]
The comment is like this:
_Address 'box-sizing' set to 'border-box' in Safari and Chrome._ [line 353]

And in the code is like this:
```css
input[type="search"]` {...
    box-sizing: content-box; /* 2 */
}
```

The correct porperty value should be **border-box**, not _content-box_, right?
