### ISSUE TITLE
Possible opportunity to combine two rules into one selector

### ISSUE THREAD

**Issue by azdavis** [necolas/normalize.css#553]
Under "Forms," I noticed this rule:

```css
/**
 * Change font properties to `inherit` in all browsers (opinionated).
 */

button,
input,
select,
textarea {
  font: inherit;
}
```

Then further down,

```css
/**
 * Remove the margin in Safari.
 * 1. Remove the margin in Firefox and Safari.
 */

button,
input,
select,
textarea { /* 1 */
  margin: 0;
}
```

Could one save a few bytes and combine the two rules into the same selector, or do they need to be separate for inheritance purposes? Or are they separate because one is "opinionated" and one is not?
