### ISSUE TITLE
the monospace font-family 

### ISSUE THREAD

**Issue by marvin1023** [necolas/normalize.css#586]
```css
/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

code,
kbd,
pre,
samp {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}
```
two `monospace`
