### ISSUE TITLE
webkit input=search has dropdown on left side when results= attribute is set

### ISSUE THREAD

**Issue by vinorodrigues** [necolas/normalize.css#590]
The webkit `input type=search` cancel selector (right side) is switched off at line 398, but not the history drop down (left side) that appears when there are history items  (results=x + autosave=uid attribute):

Possible fix is:
```css
[type="search"]::-webkit-search-cancel-button,
[type="search"]::-webkit-search-decoration,
[type="search"]::-webkit-search-results-button,
[type="search"]::-webkit-search-results-decoration {
  -webkit-appearance: none;
}
```

See ref. in [Safari docs](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-results).
