### ISSUE TITLE
Drop support for IE 8

### ISSUE THREAD

**Issue by electerious** [necolas/normalize.css#637]
I guess it's about time to drop support for IE 8. Shipping code for such an outdated browsers isn't necessary. Is this a welcome change/PR?

I would also love to remove all IE 9 related styles, but I'm sure there're still people depending on it. Any thoughts or plans to remove support for old browsers?

**Comment by battaglr** [comment]
@electerious, for IE 8 we only have one rule:

```css
/**
 * Add the correct margin in IE 8.
 */

figure {
  margin: 1em 40px;
}
```

Removing it wouldn't make a big difference:

> - With IE 8 support: 966 bytes.
> - Without IE 8 support: 956 bytes.

And regarding IE 9, I think we're not in a position to remove it yet.
