### ISSUE TITLE
Duplicated property "monospace" for "pre" tag

### ISSUE THREAD

**Issue by Igloczek** [necolas/normalize.css#657]
I had to ask if it's really necessary to have duplicated `monospace` property for `font-family` in `pre` tag.

Stylelint reporting this and I'd like to fix it or just wrap in ignore if it has some purpose.

```css
/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

pre {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}
```
