### ISSUE TITLE
`main` has been removed but is needed for IE 11

### ISSUE THREAD

**Issue by thasmo** [necolas/normalize.css#727]
```css
main {
    display: block;
}
```
is needed for IE 11 to render the element properly. Probably also for IE 10.
