### ISSUE TITLE
padding for input, button and textarea

### ISSUE THREAD

**Issue by yuheiy** [necolas/normalize.css#729]
`padding` for A, B or C differs depending on the browser. So, I think that we should normalize it.

**Comment by strider72** [comment]
Can you be more specific as to which browsers default to what padding?

**Comment by aifrim** [comment]
@strider72 Chrome Version 64.0.3282.186 (Official Build)

```css
user agent stylesheet
input:not([type]), input[type="email" i], input[type="number" i], input[type="password" i], input[type="tel" i], input[type="url" i], input[type="text" i] {
    padding: 1px 0px;
}

and 

input {
    -webkit-appearance: textfield;
    background-color: white;
    -webkit-rtl-ordering: logical;
    cursor: text;
    padding: 1px;
    border-width: 2px;
    border-style: inset;
    border-color: initial;
    border-image: initial;
}
```
