### ISSUE TITLE
Firefox sans-serif displaying as serif

### ISSUE THREAD

**Issue by sirbrad** [necolas/normalize.css#77]
It seems firefox ignores the below font setting and outputs the default serif font. It works fine if you specifically set 'Arial' or 'helvetica' before. 

``` css
html,
button,
input,
select,
textarea {
    font-family: sans-serif;
}
```
