### ISSUE TITLE
hr is Invisible

### ISSUE THREAD

**Issue by gMan1990** [necolas/normalize.css#785]
https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L55
```css
hr {
  box-sizing: content-box; /* 1 */
  height: 0; /* 1 */
  overflow: visible; /* 2 */
}
```
