### ISSUE TITLE
Range input on doesn't appear on Manjaro (linux) -  Firefox

### ISSUE THREAD

**Issue by GeoSot** [necolas/normalize.css#786]
Hello, I have faced a minor problem while I was experimenting with some form elements

The range type input doen't appear correctly in my Firefox, except if I  apply the following css rule. 

```css
input[type=range]::-moz-range-track {
  background-color: #c3c3c3;
}

```

[Codepen example](https://codepen.io/anon/pen/xoPZZz?editors=1100)

**Comment by garrettw** [comment]
I can see the track in my Firefox (on macOS), and on your Codepen I can see that your CSS doesn't match the default look. Here are my user-agent styles in case they might help you track down the correct items that are missing on your end.

(Surprisingly enough, Firefox's own inspector marks some of these property names and/or values as invalid!)

```css
input[type="range"]::-moz-focus-outer {
    border: 1px dotted black;
}
::-moz-meter-bar {
    display: inline-block !important;
    float: none !important;
    position: static !important;
    overflow: visible !important;
    -moz-appearance: meterchunk;
    height: 100%;
    width: 100%;
}
::-moz-progress-bar {
    display: inline-block !important;
    float: none !important;
    position: static !important;
    overflow: visible !important;
    box-sizing: border-box !important;
    -moz-appearance: progresschunk;
    height: 100%;
    width: 100%;
    background-color: #0064b4;
}
input[type="range"]::-moz-range-progress {
    display: block !important;
    float: none !important;
    position: static !important;
    writing-mode: unset !important;
    direction: unset !important;
    width: 0.2em;
    height: 0.2em;
    -moz-user-select: none !important;
}
input[type="range"]::-moz-range-thumb {
    -moz-appearance: range-thumb !important;
    display: block !important;
    float: none !important;
    position: static !important;
    writing-mode: unset !important;
    direction: unset !important;
    width: 1em;
    height: 1em;
    border: 0.1em solid #999;
    border-radius: 0.5em;
    background-color: #F0F0F0;
    -moz-user-select: none !important;
}
input[type="range"]::-moz-range-track {
    display: block !important;
    float: none !important;
    position: static !important;
    writing-mode: unset !important;
    direction: unset !important;
    block-size: 0.2em;
    -moz-user-select: none !important;
}
::backdrop {
    -moz-top-layer: top !important;
    display: block;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}
::cue {
    color: rgba(255, 255, 255, 1);
    white-space: pre-line;
    background-color: rgba(0, 0, 0, 0.8);
    font: var(--cue-font-size) sans-serif;
}
::marker {
    text-align: end;
    unicode-bidi: isolate;
    font-variant-numeric: tabular-nums;
}
input[type="range"] {
    -moz-appearance: range;
    display: inline-block;
    margin: 2px;
    cursor: default;
    padding: unset;
    border: unset;
    -moz-user-select: none !important;
}
input {
    -moz-appearance: textfield;
    padding: 1px;
    border: 2px inset ThreeDLightShadow;
    background-color: -moz-Field;
    color: -moz-FieldText;
    font: -moz-field;
        line-height: normal;
    text-rendering: optimizeLegibility;
    line-height: normal;
    text-align: start;
    text-transform: none;
    word-spacing: normal;
    letter-spacing: normal;
    cursor: text;
    text-indent: 0;
    -moz-user-select: text;
    text-shadow: none;
    overflow-clip-box: padding-box content-box;
}

```
