### ISSUE TITLE
Suggestion: reset - ul, ol, li, menu and dir

### ISSUE THREAD

**Issue by FDiskas** [necolas/normalize.css#787]
Google chrome `Version 73.0.3683.86`  User agent stylesheet
```css
ul, menu, dir {
    display: block;
    list-style-type: disc;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    padding-inline-start: 40px;
}
```
```css
ol {
    display: block;
    list-style-type: decimal;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    padding-inline-start: 40px;
}
```
```css
li {
    display: list-item;
    text-align: -webkit-match-parent;
}
```
