### ISSUE TITLE
May I suggest updating abbr[title] to add support for Safari?

### ISSUE THREAD

**Issue by simevidas** [necolas/normalize.css#819]
normalize.css includes the following style rule:

```css
/**
 * 1. Remove the bottom border in Chrome 57-
 * 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
 */

abbr[title] {
  border-bottom: none; /* 1 */
  text-decoration: underline; /* 2 */
  text-decoration: underline dotted; /* 2 */
}
```

Source: https://github.com/necolas/normalize.css/blob/master/normalize.css#L80-L89

This results in a *solid* underline in Safari:

<img width="707" alt="Screen Shot 2020-06-02 at 6 29 52 PM" src="https://user-images.githubusercontent.com/716405/83545713-decfd680-a4ff-11ea-9ebe-87a155858d7d.png">

However, Safari does support `text-decoration-style`. You could add the following declaration to the above style rule to make the underline dotted in Safari as well:

```css
text-decoration-style: dotted;
```

Demo: https://jsbin.com/guriqel/edit?html,css,output

Could you check if this is something that you could do?

**Comment by juytter** [comment]
#738

**Comment by sean1138** [comment]
I'm not sure that there is anything that can be done for this as far as normalize.css goes but thought it might be noteworthy. 

I noticed some oddness with the dotted underline in chrome with a three letter acronym.  At first i thought it was just because the content was all caps but no.  Changing the font-size can change/improve the appearance of the dotted underline IMO, at around `font-size:21px` the dotted underline looks better in chrome here.  Using 5 letters saw unexpected results in chrome here as well.
https://codepen.io/sean1138/pen/dyGeKK
![2020 07 09_071853](https://user-images.githubusercontent.com/6720184/87033611-83ef6600-c1b4-11ea-9d06-38a503ac2c3f.jpg)

**Comment by garrettw** [comment]
@simevidas is this fix still needed in Safari?

**Comment by simevidas** [comment]
@garrettw Yes, it’s needed. Safari 16.3 still does not support the shorthand `text-decoration: underline dotted`.

The relevant WebKit bug is here: https://bugs.webkit.org/show_bug.cgi?id=230083

**Comment by garrettw** [comment]
Ok, adding it to my normalize in https://github.com/garrettw/vitals

**Comment by olivier3lanc** [comment]
May found a way to a consistent display for Firefox, Chrome and Safari

```css
abbr[title] {
    text-decoration-style: dotted;
    text-decoration: underline;
    text-decoration: underline dotted;
}
```
demo https://codepen.io/olivier3lanc/pen/Pwwmrod
